// <auto-generated />
using System;
using AgencyFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgencyFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgencyFlow.Models.ClientCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid?>("RepresentativeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepresentativeUserId");

                    b.ToTable("ClientCompanies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empresa cliente del sector tecnologia y dispositivos moviles.",
                            Name = "Honor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empresa cliente del sector deportivo y moda.",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empresa cliente del sector telecomunicaciones.",
                            Name = "Tigo"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Medios tradicionales: TV, radio, prensa y via publica.",
                            Name = "ATL"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estrategia y ejecucion de campanas en medios digitales.",
                            Name = "Digital"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diseno grafico y produccion visual de piezas.",
                            Name = "Diseno"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conceptualizacion creativa de campanas y contenidos.",
                            Name = "Creatividad"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generacion de contenido para redes y plataformas digitales.",
                            Name = "Content"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gestion y seguimiento directo de las cuentas de clientes.",
                            Name = "Ejecutivo de cuenta"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Direccion y gestion general de la empresa.",
                            Name = "Gerencia"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.DepartmentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDirector")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("DepartmentUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222207"),
                            IsDirector = false,
                            UserId = new Guid("44444444-4444-4444-4444-444444444401")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            IsDirector = true,
                            UserId = new Guid("44444444-4444-4444-4444-444444444402")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            IsDirector = true,
                            UserId = new Guid("44444444-4444-4444-4444-444444444403")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            IsDirector = true,
                            UserId = new Guid("44444444-4444-4444-4444-444444444403")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            IsDirector = false,
                            UserId = new Guid("44444444-4444-4444-4444-444444444407")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            IsDirector = false,
                            UserId = new Guid("44444444-4444-4444-4444-444444444408")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222206"),
                            IsDirector = false,
                            UserId = new Guid("44444444-4444-4444-4444-444444444409")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            IsDirector = false,
                            UserId = new Guid("44444444-4444-4444-4444-444444444410")
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DedupeKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "DedupeKey")
                        .IsUnique()
                        .HasFilter("\"DedupeKey\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AgencyFlow.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClientUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            ClientUserId = new Guid("44444444-4444-4444-4444-444444444404"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Campana integral de branding y marketing para el lanzamiento del nuevo modelo.",
                            EndDate = new DateOnly(2026, 8, 31),
                            ProjectTypeId = new Guid("55555555-5555-5555-5555-555555555501"),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "Pendiente",
                            Title = "Campana de lanzamiento Honor X10"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666602"),
                            ClientUserId = new Guid("44444444-4444-4444-4444-444444444405"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Produccion audiovisual de spot para campana de la linea de running.",
                            ProjectTypeId = new Guid("55555555-5555-5555-5555-555555555503"),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            Title = "Spot publicitario Adidas Running"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666603"),
                            ClientUserId = new Guid("44444444-4444-4444-4444-444444444406"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Planificacion y compra de espacios publicitarios para el tercer trimestre.",
                            EndDate = new DateOnly(2026, 9, 30),
                            ProjectTypeId = new Guid("55555555-5555-5555-5555-555555555504"),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            Title = "Plan de medios Tigo Q3"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.ProjectDirectorAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DirectorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DirectorUserId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("ProjectId", "DirectorUserId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("ProjectDirectorAccesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DirectorUserId = new Guid("44444444-4444-4444-4444-444444444402"),
                            GrantedByUserId = new Guid("44444444-4444-4444-4444-444444444401"),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666601")
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.ProjectStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("project_status_history", (string)null);
                });

            modelBuilder.Entity("AgencyFlow.Models.ProjectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Proyectos de construccion e identidad de marca.",
                            Name = "Branding"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estrategias y campanas de marketing en general.",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Produccion de video, fotografia y contenido audiovisual.",
                            Name = "Produccion Audiovisual"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Planificacion y compra de espacios publicitarios.",
                            Name = "Medios Publicitarios"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Usuario externo que representa a una empresa cliente.",
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Responsable de la gestion general y toma de decisiones.",
                            Name = "Gerente"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lidera un area o departamento de la empresa.",
                            Name = "Director"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal operativo con mayor nivel de experiencia.",
                            Name = "Operativo 1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal operativo de nivel inicial.",
                            Name = "Operativo 2"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estudiante en formacion practica dentro de la empresa.",
                            Name = "Pasante"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrador tecnico con acceso completo.",
                            Name = "SuperUsuario"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.SubProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("SubProjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777701"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Detail = "Creacion de banners, posts y material grafico para la campana.",
                            EndDate = new DateOnly(2026, 6, 20),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666601"),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "En curso",
                            Title = "Diseno de piezas graficas - Lanzamiento Honor X10"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777702"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Detail = "Desarrollo creativo del concepto y guion para el spot audiovisual.",
                            EndDate = new DateOnly(2026, 7, 10),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666602"),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            Title = "Guion y storyboard - Spot Adidas Running"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777703"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Detail = "Negociacion y reserva de espacios publicitarios para el trimestre.",
                            EndDate = new DateOnly(2026, 8, 1),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666603"),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            Title = "Compra de espacios en medios - Tigo Q3"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.SubProjectStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("SubProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubProjectId", "Timestamp");

                    b.ToTable("subproject_status_history", (string)null);
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("SubTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999901"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Definir colores acorde a la identidad de marca de Honor.",
                            EndDate = new DateOnly(2026, 6, 2),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "Completada",
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888801"),
                            Title = "Seleccionar paleta de colores"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999902"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Buscar referencias de spots similares para inspiracion del guion.",
                            EndDate = new DateOnly(2026, 7, 2),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888802"),
                            Title = "Investigar referencias narrativas"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999903"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Armar lista de proveedores y solicitar datos de contacto.",
                            EndDate = new DateOnly(2026, 7, 16),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888803"),
                            Title = "Contactar proveedores de vallas"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("SubTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("SubTaskComments");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTaskStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<Guid>("SubTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("subtask_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("SubTaskId", "Timestamp");

                    b.ToTable("subtask_status_history", (string)null);
                });

            modelBuilder.Entity("AgencyFlow.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OwnProgressPercentage")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("SubProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888801"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Banner para Instagram y Facebook con las dimensiones requeridas por campana.",
                            EndDate = new DateOnly(2026, 6, 5),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "En curso",
                            SubProjectId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Title = "Disenar banner principal para redes"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888802"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Primera version del guion narrativo para revision del cliente.",
                            EndDate = new DateOnly(2026, 7, 4),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            SubProjectId = new Guid("77777777-7777-7777-7777-777777777702"),
                            Title = "Redactar guion del spot"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888803"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Solicitar cotizaciones a proveedores de espacios publicitarios.",
                            EndDate = new DateOnly(2026, 7, 20),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            SubProjectId = new Guid("77777777-7777-7777-7777-777777777703"),
                            Title = "Cotizar espacios en via publica"
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.TaskStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Timestamp");

                    b.ToTable("task_status_history", (string)null);
                });

            modelBuilder.Entity("AgencyFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientCompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gerencia.demo@example.com",
                            FirstName = "Demo",
                            LastName = "Gerencia",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "directora.digital@example.com",
                            FirstName = "Demo",
                            LastName = "Directora Digital",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "director.creativo@example.com",
                            FirstName = "Demo",
                            LastName = "Director Creativo",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            ClientCompanyId = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Demo",
                            LastName = "Cliente Honor",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            ClientCompanyId = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Demo",
                            LastName = "Cliente Adidas",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            ClientCompanyId = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Demo",
                            LastName = "Cliente Tigo",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operativo.diseno@example.com",
                            FirstName = "Demo",
                            LastName = "Operativo Diseno",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operativo.junior@example.com",
                            FirstName = "Demo",
                            LastName = "Operativo Junior",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111105")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operativo.ejecutivo@example.com",
                            FirstName = "Demo",
                            LastName = "Operativo Ejecutivo",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pasante.atl@example.com",
                            FirstName = "Demo",
                            LastName = "Pasante ATL",
                            Password = "DISABLED_DEMO_ACCOUNT",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104")
                        });
                });

            modelBuilder.Entity("AgencyFlow.Models.ClientCompany", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "RepresentativeUser")
                        .WithMany()
                        .HasForeignKey("RepresentativeUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RepresentativeUser");
                });

            modelBuilder.Entity("AgencyFlow.Models.DepartmentUser", b =>
                {
                    b.HasOne("AgencyFlow.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyFlow.Models.User", "User")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyFlow.Models.Notification", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyFlow.Models.Project", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "ClientUser")
                        .WithMany()
                        .HasForeignKey("ClientUserId");

                    b.HasOne("AgencyFlow.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("AgencyFlow.Models.ProjectDirectorAccess", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "DirectorUser")
                        .WithMany()
                        .HasForeignKey("DirectorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyFlow.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgencyFlow.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorUser");

                    b.Navigation("GrantedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AgencyFlow.Models.ProjectStatusHistory", b =>
                {
                    b.HasOne("AgencyFlow.Models.Project", "Project")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubProject", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("AgencyFlow.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyFlow.Models.Project", "Project")
                        .WithMany("SubProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubProjectStatusHistory", b =>
                {
                    b.HasOne("AgencyFlow.Models.SubProject", "SubProject")
                        .WithMany("StatusHistory")
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTask", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("AgencyFlow.Models.TaskItem", "TaskItem")
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTaskComment", b =>
                {
                    b.HasOne("AgencyFlow.Models.SubTask", "SubTask")
                        .WithMany("Comments")
                        .HasForeignKey("SubTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyFlow.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTaskStatusHistory", b =>
                {
                    b.HasOne("AgencyFlow.Models.SubTask", "SubTask")
                        .WithMany("StatusHistory")
                        .HasForeignKey("SubTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTask");
                });

            modelBuilder.Entity("AgencyFlow.Models.TaskItem", b =>
                {
                    b.HasOne("AgencyFlow.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("AgencyFlow.Models.SubProject", "SubProject")
                        .WithMany("TaskItems")
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("AgencyFlow.Models.TaskStatusHistory", b =>
                {
                    b.HasOne("AgencyFlow.Models.TaskItem", "Task")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AgencyFlow.Models.User", b =>
                {
                    b.HasOne("AgencyFlow.Models.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId");

                    b.HasOne("AgencyFlow.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AgencyFlow.Models.Project", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("SubProjects");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubProject", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("AgencyFlow.Models.SubTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("AgencyFlow.Models.TaskItem", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("AgencyFlow.Models.User", b =>
                {
                    b.Navigation("DepartmentUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
